### ISSUE TITLE
Could not load this custom viewer

### ISSUE THREAD

**Issue by satabol** [zspitz/ANTLR4ParseTreeVisualizer#50] opened 2019-11-14 05:11 UTC
Hello. 
After [install](https://github.com/zspitz/ANTLR4ParseTreeVisualizer#installation) this viewer got error on runtime:
![image](https://user-images.githubusercontent.com/14288520/68828119-8fd26900-06b5-11ea-8189-024c089a053e.png)

**Comment by zspitz** [comment] 2019-11-14 05:24
Are you saying the visualizer only works with Managed Compatibility Mode turned off?

* What version of VS are you using?
* Are you using the Antlr / Antlr.Runtime NuGet package? Or the Antlr.Runtime.Standard package? Which version?
* Is this a .NET Framework project, or a .NET Core project?
* Which language?

**Comment by satabol** [comment] 2019-11-14 06:04
What version of VS are you using?
Visual Studio 2019 Professional

Are you using the Antlr / Antlr.Runtime NuGet package? Or the Antlr.Runtime.Standard package? Which version?
I'm using Antlr.Runtime NuGet package - Antlr4.Runtime.Standard 4.7.2, Antlr4BuildTasks 1.0.8

Is this a .NET Framework project, or a .NET Core project?
.NET Framework 4.6.2

Which language?
C#

**Comment by zspitz** [comment] 2019-11-14 08:58
I'm unable to reproduce on a .NET 4.6.2 project, as I am unable to debug at all with Managed Compatibility Mode on.

@satabol, is turning off Managed Compatibility Mode a good workaround for you?

**Comment by satabol** [comment] 2019-11-14 09:10
> is turning off Managed Compatibility Mode a good workaround for you?
Yes. When I set On then I get error again.
An addition - I have a WPF  project.

**Comment by zspitz** [comment] 2019-11-14 10:30
So I'll make note of this in the README, and close this issue.

**Closed by zspitz** 2019-11-14 10:30 UTC

**Comment by satabol** [comment] 2019-11-14 13:35
> I'll make note of this in the README, and close this issue

Ok. Thank you.
